<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>Assets\icon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Assets\AnytimeFitnessLogo.jpg" />
    <None Remove="Assets\Developer.jpg" />
    <None Remove="Assets\logo.jpg" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\icon.ico" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Themes\" />
    <Folder Include="Templates\" />
    <Folder Include="Resources\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="JpProject.AspNetCore.PasswordHasher.Bcrypt" Version="3.0.3" />
    <PackageReference Include="LiveChartsCore.SkiaSharpView" Version="2.0.4" />
    <PackageReference Include="LiveChartsCore.SkiaSharpView.WPF" Version="2.0.4" />
    <PackageReference Include="Microsoft.AspNetCore.Identity" Version="2.3.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.8" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.8" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.8">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.9" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.9" />
    <PackageReference Include="PDFsharp" Version="6.2.4" />
    <PackageReference Include="QRCoder" Version="1.8.0" />
    <PackageReference Include="QuestPDF" Version="2026.5.0" />
    <PackageReference Include="SkiaSharp" Version="3.119.4" />
    <PackageReference Include="System.Data.SqlClient" Version="4.9.1" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\AnytimeFitnessLogo.jpg">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Developer.jpg">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\logo.jpg">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

  <ItemGroup>
    <None Update="Assets\logo - Copy.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
